name: extension-manager # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.4.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: A utility for browsing and installing GNOME Shell Extensions. # 79 char long summary
description: |
  A native tool for browsing, installing, and managing GNOME Shell Extensions. Written with GTK 4 and libadwaita.
  
architectures:
  - amd64
  - arm64
  
# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0
  title: Extension Manager

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  extension-manager:
    command: usr/bin/extension-manager
    extensions: [gnome]
    desktop: usr/share/applications/com.mattjakeman.ExtensionManager.desktop
    plugs:
      - network
      - network-bind
      - network-status
    
slots:
  # for GtkApplication registration
  extension-manager:
    interface: dbus
    bus: session
    name: com.mattjakeman.ExtensionManager

parts:
  extension-manager:
    source: .
    
    override-pull: |
      snapcraftctl pull
      sed -i -e 's|@app_id@|/usr/share/icons/hicolor/scalable/apps/com.mattjakeman.ExtensionManager.svg|g' data/com.mattjakeman.ExtensionManager.desktop.in.in

    plugin: meson
    build-packages:
      - blueprint-compiler
      - libtext-engine-dev
      - meson
    meson-parameters:
      - --prefix=/usr
    stage-packages:
      - libtext-engine-0.1-0
    
#   cleanup:
#     after:  # Make this part run last; list all your other parts here
#       - extension-manager
#     plugin: nil
#     build-snaps:  # List all content-snaps and base snaps you're using here
#       - core22
#       - gtk-common-themes 
#       - gnome-42-2204
#     override-prime: |
#       set -eux
#       for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
#           cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
#       done
