on:
  push:
    branches: [master]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: extension-manager.flatpak
        manifest-path: com.mattjakeman.ExtensionManager.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
        run-tests: true
